<a href="https://colab.research.google.com/github/dinhngocquan/AI-Fundamentals/blob/main/Chapter1/1_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.   NumPy library:

## 1.1. NumPy basics:

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
arr1=np.array([1,3,5,7,9])
arr2=np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [3]:
arr3=arr1

In [4]:
id(arr1)

135124391131344

In [5]:
id(arr3)

135124391131344

In [6]:
arr4=arr1.copy()

In [7]:
id(arr4)

135124391664736

## 1.2. Creating NumPy arrays:

numpy.arange() function:

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [13]:
arr=np.arange(10)

In [14]:
len(arr)

10

In [15]:
arr.size

10

numpy.linspace() function:

In [16]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
arr=np.linspace(1,10,5,retstep=True)
np.linspace(1,10,5,retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), np.float64(2.25))

In [21]:
type(arr)

tuple

In [20]:
arr[0]

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
arr[1]

np.float64(2.25)

numpy.zeros() and numpy.ones() functions:

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros(5, dtype='int64')

array([0, 0, 0, 0, 0])

In [27]:
np.zeros(5, dtype='int64').dtype

dtype('int64')

In [28]:
arr=np.ones((2,3), dtype='int_')

In [29]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
arr.dtype

dtype('int64')

In [31]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Data type:

In [32]:
arr1=np.array([111,2.3,True,False,False])
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [33]:
arr2=np.array([111,2.3,'python','abc'])
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [34]:
arr3=np.array([111,True,'abc'])
arr3

array(['111', 'True', 'abc'], dtype='<U21')

## 1.3. Indexing and slicing NumPy arrays:

In [41]:
a=np.array([1,2,3,4,5])
a[2]

np.int64(3)

In [42]:
a[-1]

np.int64(5)

In [43]:
a[:]

array([1, 2, 3, 4, 5])

In [46]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a[1]

array([4, 5, 6])

In [48]:
a[-1]

array([7, 8, 9])

In [49]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a[2][1]

np.int64(8)

In [51]:
a[2,1]

np.int64(8)

In [52]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [53]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing:

In [56]:
arr=np.arange(100)

In [59]:
arrMask=((arr % 5)==0)
arrMask

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False])

In [58]:
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

## 1.4. NumPy attributes and reshaping:

In [60]:
a.size

9

In [61]:
a.shape

(3, 3)

In [62]:
a.ndim

2

Change the shape with reshape() method:

In [63]:
a=np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
a=np.array([2,5,1,3])
a.shape

(4,)

In [69]:
a=a.reshape((2,2))
a.shape

(2, 2)

Careful that the reshape() method does not create a new object!

In [71]:
a=np.arange(10)
b=a.reshape(2,5)
a[0]=-999

In [72]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [73]:
c=a.reshape(2,5).copy()
c[0,0]=0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

## 1.5. Modifying NumPy arrays:

Appending elements, rows and columns to arrays:

In [74]:
a=np.array([1,2,3])
b=np.append(a,[4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [78]:
a=np.array([[1,2],[3,4]])
b=np.append(a,[[9,9]],axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [79]:
c=np.append(a,[[9],[9]], axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

Deleting array elements, rows and columns:

In [80]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a,0)

array([2, 3, 4, 5, 6])

In [81]:
np.delete(a,(0,2,4))

array([2, 4, 6])

In [82]:
np.delete(a,0,axis=0)

array([[4, 5, 6]])

In [83]:
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6]])