<a href="https://colab.research.google.com/github/dinhngocquan/AI-Fundamentals/blob/main/Chapter1/3_numpy_indexing_boolean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Added to the existing codes

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
a[:2]

array([1, 2])

In [4]:
a[-1]

np.int64(5)

In [5]:
a[:]

array([1, 2, 3, 4, 5])

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
a[1]

array([4, 5, 6])

In [8]:
a[-1]

array([7, 8, 9])

In [9]:
a[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a[2][1]

np.int64(8)

In [12]:
a[2,1]

np.int64(8)

In [13]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [14]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing

In [15]:
arr=np.arange(100)

In [16]:
arrMask=((arr%5)==0)

In [17]:
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [18]:
arrMask=(((arr%5)==0)&(arr>0))

In [19]:
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

Boolean Indexing

In [20]:
test_a = np.array([1,4,0,2,3,8,9,7])

In [21]:
test_a

array([1, 4, 0, 2, 3, 8, 9, 7])

In [22]:
test_a>3

array([False,  True, False, False, False,  True,  True,  True])

In [23]:
test_a[test_a>3]

array([4, 8, 9, 7])