<a href="https://colab.research.google.com/github/dinhngocquan/AI-Fundamentals/blob/main/Chapter1/4_numpy_array_transposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array Transposition

In [2]:
import numpy as np

In [3]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr=np.random.randn(6,3)
arr

array([[ 1.65999846,  0.27107162, -1.60669353],
       [ 0.51289177, -0.80889481, -1.20224934],
       [-0.88537961, -0.34587669, -1.10337366],
       [-0.23801493, -1.25972123,  0.42799301],
       [-0.04363786,  0.96193239, -0.87980616],
       [-1.67877858, -1.4018336 , -0.2912912 ]])

In [6]:
np.dot(arr.T,arr)

array([[ 6.67940279,  2.95255916, -1.88129048],
       [ 2.95255916,  5.32477026, -0.05852868],
       [-1.88129048, -0.05852868,  6.28638845]])

In [7]:
arr=np.arange(16).reshape(2,2,4)

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [10]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [11]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])